version: AppVeyor build {build}
shallow_clone: true
image: Ubuntu
install:
- sh: >-
    git clone https://github.com/aboood40091/SARC-Tool.git

    echo -en "\n\n" |sudo apt install python3-pip

    sudo pip3 install SarcLib

    sudo pip3 install libyaz0

build_script:
- sh: >-
    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release

    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release

    mkdir -p Release/MSG/TitleID/Romfs/Message

    mkdir -p Release/OE-Sound/sub/OE-TitleID/Romfs/Sound/Resource/Stream

    mkdir -p Release/Sound/sub/OE-TitleID/Romfs/Sound/Resource/Stream

    mkdir -p Release/Model/TitleID/Romfs/Model

    mkdir -p Release/OE-Model/OE-TitleID/Romfs/Model

    mv 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release.szs Release/MSG/TitleID/Romfs/Message/LayoutMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release.szs Release/MSG/TitleID/Romfs/Message/CommonMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Sound/Resource/Stream Release/Sound/sub/TitleID/Romfs/Sound/Resource

    mv 01003bc0000a0000/Romfs/Model Release/Model/TitleID/Romfs

    mv 01003bc0000a1065/Romfs/Model Release/OE-Model/OE-TitleID/Romfs

    mv 01003bc0000a1065/Romfs/Sound/Resource/Stream Release/OE-Sound/sub/OE-TitleID/Romfs/Sound/Resource

    cd ${APPVEYOR_BUILD_FOLDER}/Release/OE-Sound/sub

    zip -9 -r OE-Sound *

    cd ${APPVEYOR_BUILD_FOLDER}/Release/Sound/sub

    zip -9 -r Sound *

    curl --Output OE-Sound.txt --upload-file ${APPVEYOR_BUILD_FOLDER}/Release/OE-Sound/sub/OE-Sound.zip https://transfer.sh/OE-Sound.zip

    curl --Output Sound.txt --upload-file ${APPVEYOR_BUILD_FOLDER}/Release/Sound/sub/Sound.zip https://transfer.sh/Sound.zip
artifacts:
- path: Release\MSG
- path: Release\Model
- path: Release\Sound\sub\Sound.txt
- path: Release\Sound\sub\OE-Sound.txt
- path: Release\OE-Model
deploy: off
