version: AppVeyor build {build}
shallow_clone: true
image: Ubuntu
install:
- sh: >-
    git clone https://github.com/aboood40091/SARC-Tool.git

    echo -en "\n\n" |sudo apt install python3-pip

    sudo apt-get install p7zip-full p7zip-rar

    sudo pip3 install SarcLib

    sudo pip3 install libyaz0

build_script:
- sh: >-
    rm 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release/*.lot

    rm 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release/*.lot

    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release

    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release

    mkdir -p Release/Message/TitleID/Romfs/Message

    mkdir -p Release/OE-Sound/OE-TitleID/Romfs/Sound/Resource/Stream

    mkdir -p Release/Sound/TitleID/Romfs

    mkdir -p Release/Model/TitleID/Romfs/Model

    mkdir -p Release/OE-Model/OE-TitleID/Romfs/Model

    cp README.md Release/Message/README.md

    cp README.md Release/OE-Model/README.md

    cp README.md Release/Model/TitleID/Romfs/README.md

    cp README.md Release/OE-Sound/README.md

    cp README.md Release/Sound/README.md

    mv 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release.szs Release/Message/TitleID/Romfs/Message/LayoutMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release.szs Release/Message/TitleID/Romfs/Message/CommonMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Sound Release/Sound/TitleID/Romfs/

    mv 01003bc0000a0000/Romfs/Model Release/Model/TitleID/Romfs

    mv 01003bc0000a1065/Romfs/Model Release/OE-Model/OE-TitleID/Romfs

    mv 01003bc0000a1065/Romfs/Sound/Resource/Stream Release/OE-Sound/OE-TitleID/Romfs/Sound/Resource

    7z a -t7z OE-Sound.7z ${APPVEYOR_BUILD_FOLDER}/Release/OE-Sound

    7z a -t7z Sound.7z ${APPVEYOR_BUILD_FOLDER}/Release/Sound

    7z a -t7z Sound.7z ${APPVEYOR_BUILD_FOLDER}/Release/OE-Model

    7z a -t7z Sound.7z ${APPVEYOR_BUILD_FOLDER}/Release/Model

    7z a -t7z Sound.7z ${APPVEYOR_BUILD_FOLDER}/Release/Message

    curl --Output OE-Sound.txt --upload-file ${APPVEYOR_BUILD_FOLDER}/Release/OE-Sound/OE-Sound.7z https://transfer.sh/OE-Sound.zip

    curl --Output Sound.txt --upload-file ${APPVEYOR_BUILD_FOLDER}/Release/Sound/Sound.7z https://transfer.sh/Sound.zip
artifacts:
- path: Release\Message.7z
- path: Release\Model.7z
- path: Release\Sound\Sound.txt
- path: Release\Sound\OE-Sound.txt
- path: Release\OE-Model.7z
deploy: off
