version: AppVeyor build {build}
shallow_clone: true
image: Ubuntu
install:
- sh: >-
    git clone https://github.com/aboood40091/SARC-Tool.git

    sudo apt install python2
    
    sudo python3 -m pip install SarcLib

    sudo python3 -m pip install libyaz0
build_script:
- sh: >-
    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release

    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release

    mkdir -p Release/MSG/TitleID/Romfs/Message

    mkdir -p Release/OE-Sound/TitleID/Romfs/Sound/Resource/Stream

    mkdir -p Release/Sound/TitleID/Romfs/Sound/Resource/Stream

    mkdir -p Release/Model/TitleID/Romfs/Model

    mv 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release.szs Release/MSG/TitleID/Romfs/Message/LayoutMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release.szs Release/MSG/TitleID/Romfs/Message/CommonMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Sound/Resource/Stream Release/Sound/TitleID/Romfs/Sound/Resource/Stream

    mv 01003bc0000a0000/Romfs/Model Release/Model/TitleID/Romfs/Model

    mv 01003bc0000a1065/Romfs/Sound/Resource/Stream Release/OE-Sound/TitleID/Romfs/Sound/Resource/Stream
artifacts:
- path: Release\MSG
- path: Release\Model
deploy: off
